name: Build

on:
  push:
    branches:
      - master
      - actions-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make build script executable
        run: chmod +x source/build.sh

      - name: Run build script
        run: ./source/build.sh

      - name: Commit and push changes to install.sh
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add -f install.sh
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update build/install.sh"
            git push
          fi
